### Oleksiy Anokhin (August 9, 2020)

### MSCA 37014 | Python for Analytics | Professor S. Chaudhary | Homework 3 (Team Project) | Data Cleaning

In [13]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set additional parameters
# Remove column display limits
pd.set_option('display.max_columns', None)
# pd.set_option('display.height', None)
pd.set_option('display.max_rows', None)
# pd.set_option('display.width', None)
plt.rcParams['figure.figsize'] = [15, 10]
sns.set_style("white")

In [14]:
# Read data
project = pd.read_csv('../Data/Raw/PERM_FY2020_Q3.csv', encoding = 'ISO-8859-1')

C:\Users\mattk\anaconda3\envs\msca\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (16,19,85,122) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
# Print data
project.head(5)

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,ORIG_FILE_DATE,PREVIOUS_SWA_CASE_NUMBER_STATE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,EMPLOYER_ADDRESS_2,EMPLOYER_CITY,EMPLOYER_STATE_PROVINCE,EMPLOYER_COUNTRY,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,EMPLOYER_PHONE_EXT,EMPLOYER_NUM_EMPLOYEES,EMPLOYER_YEAR_COMMENCED_BUSINESS,NAICS_CODE,FW_OWNERSHIP_INTEREST,EMP_CONTACT_NAME,EMP_CONTACT_ADDRESS_1,EMP_CONTACT_ADDRESS_2,EMP_CONTACT_CITY,EMP_CONTACT_STATE_PROVINCE,EMP_CONTACT_COUNTRY,EMP_CONTACT_POSTAL_CODE,EMP_CONTACT_PHONE,EMP_CONTACT_EMAIL,AGENT_ATTORNEY_NAME,AGENT_ATTORNEY_FIRM_NAME,AGENT_ATTORNEY_PHONE,AGENT_ATTORNEY_PHONE_EXT,AGENT_ATTORNEY_ADDRESS_1,AGENT_ATTORNEY_ADDRESS_2,AGENT_ATTORNEY_CITY,AGENT_ATTORNEY_STATE_PROVINCE,AGENT_ATTORNEY_COUNTRY,AGENT_ATTORNEY_POSTAL_CODE,AGENT_ATTORNEY_EMAIL,PW_TRACK_NUMBER,PW_SOC_CODE,PW_SOC_TITLE,PW_SKILL_LEVEL,PW_WAGE,PW_UNIT_OF_PAY,PW_WAGE_SOURCE,PW_SOURCE_NAME_OTHER,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_TO,WAGE_OFFER_UNIT_OF_PAY,WORKSITE_ADDRESS_1,WORKSITE_ADDRESS_2,WORKSITE_CITY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,JOB_TITLE,MINIMUM_EDUCATION,JOB_EDUCATION_MIN_OTHER,MAJOR_FIELD_OF_STUDY,REQUIRED_TRAINING,REQUIRED_TRAINING_MONTHS,REQUIRED_FIELD_OF_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,ACCEPT_ALT_FIELD_OF_STUDY,ACCEPT_ALT_MAJOR_FLD_OF_STUDY,ACCEPT_ALT_COMBO,ACCEPT_ALT_COMBO_EDUCATION,ACCEPT_ALT_COMBO_ED_OTHER,ACCEPT_ALT_COMBO_EDUCATION_YRS,ACCEPT_FOREIGN_EDUCATION,ACCEPT_ALT_OCCUPATION,ACCEPT_ALT_OCCUPATION_MONTHS,ACCEPT_ALT_JOB_TITLE,JOB_OPP_REQUIREMENTS_NORMAL,FOREIGN_LANGUAGE_REQUIRED,SPECIFIC_SKILLS,COMBINATION_OCCUPATION,OFFERED_TO_APPL_FOREIGN_WORKER,FOREIGN_WORKER_LIVE_ON_PREM,FOREIGN_WORKER_LIVE_IN_DOM_SER,FOREIGN_WORKER_LIVE_IN_DOM_CNT,PROFESSIONAL_OCCUPATION,APP_FOR_COLLEGE_U_TEACHER,COMPETITIVE_PROCESS,BASIC_RECRUITMENT_PROCESS,TEACHER_SELECT_DATE,TEACHER_PUB_JOURNAL_NAME,ADD_RECRUIT_INFORMATION,SWA_JOB_ORDER_START_DATE,SWA_JOB_ORDER_END_DATE,SUNDAY_EDITION_NEWSPAPER,FIRST_NEWSPAPER_NAME,FIRST_ADVERTISEMENT_START_DATE,SECOND_NEWSPAPER_AD_NAME,SECOND_ADVERTISEMENT_TYPE,SECOND_AD_START_DATE,JOB_FAIR_FROM_DATE,JOB_FAIR_TO_DATE,ON_CAMPUS_RECRUITING_FROM_DATE,ON_CAMPUS_RECRUITING_TO_DATE,EMPLOYER_WEBSITE_FROM_DATE,EMPLOYER_WEBSITE_TO_DATE,PRO_ORG_AD_FROM_DATE,PRO_ORG_ADVERTISEMENT_TO_DATE,JOB_SEARCH_WEBSITE_FROM_DATE,JOB_SEARCH_WEBSITE_TO_DATE,PVT_EMPLOYMENT_FIRM_FROM_DATE,PVT_EMPLOYMENT_FIRM_TO_DATE,EMPLOYEE_REF_PROG_FROM_DATE,EMPLOYEE_REFERRAL_PROG_TO_DATE,CAMPUS_PLACEMENT_FROM_DATE,CAMPUS_PLACEMENT_TO_DATE,LOCAL_ETHNIC_PAPER_FROM_DATE,LOCAL_ETHNIC_PAPER_TO_DATE,RADIO_TV_AD_FROM_DATE,RADIO_TV_AD_TO_DATE,EMP_RECEIVED_PAYMENT,PAYMENT_DETAILS,BARGAINING_REP_NOTIFIED,POSTED_NOTICE_AT_WORKSITE,LAYOFF_IN_PAST_SIX_MONTHS,US_WORKERS_CONSIDERED,COUNTRY_OF_CITIZENSHIP,FOREIGN_WORKER_BIRTH_COUNTRY,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_EDUCATION_OTHER,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_YRS_ED_COMP,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_ADD_1,FOREIGN_WORKER_ED_INST_ADD_2,FOREIGN_WORKER_ED_INST_CITY,FOREIGN_WORKER_ED_INST_STATE_P,FOREIGN_WORKER_ED_INST_COUNTRY,FOREIGN_WORKER_ED_INST_POST_CD,FOREIGN_WORKER_TRAINING_COMP,FOREIGN_WORKER_REQ_EXPERIENCE,FOREIGN_WORKER_ALT_ED_EXP,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION,PREPARER_NAME,PREPARER_TITLE,PREPARER_EMAIL,EMP_INFO_DECL_NAME,EMP_INFO_DECL_TITLE
0,A-09245-62715,Denied,9/3/2009,4/30/2020,N,NaN,NaN,N,SATURN ENTERPRISES INC,2340 N WASHTENAW AVE,NaN,CHICAGO,ILLINOIS,UNITED STATES OF AMERICA,60647,7732769550,NaN,2.0,1998.0,23611,N,zygmunt f oparowski,2340 n washtenaw ave,NaN,chicago,ILLINOIS,UNITED STATES OF AMERICA,60647,7732769550,saturn_enterprises@yahoo.com,Christopher E Kurczaba,Kurczaba Law Offices,7737740011,NaN,6219 N Milwaukee Ave,NaN,Chicago,ILLINOIS,UNITED STATES OF AMERICA,60646,kurczabalaw@sbcglobal.net,NaN,43-6011.00,administrative assistant,Level I,$14.49,Hour,OES,NaN,6/30/2009,9/28/2009,$14.49,NaN,Hour,2340 N. Washtenaw Ave,NaN,Chicago,ILLINOIS,60647,administrative assistant,High School,NaN,NaN,N,NaN,NaN,Y,24.0,N,NaN,N,NaN,NaN,NaN,Y,N,NaN,NaN,Y,Y,must communicate in Polish,N,Y,N,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,6/23/2009,7/27/2009,Y,Chicago Tribune,7/5/2009,Chicago Tribune,Newspaper,7/12/2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,Y,N,NaN,POLAND,POLAND,B-2,High School,NaN,GENERAL,1996.0,LICEUM EKONOMICZNE,UL. JANA GOETZA,NaN,BRZESKO,NaN,POLAND,32-800,NaN,Y,NaN,NaN,N,N,N,N,Christopher E Kurczaba,Attorney,kurczabalaw@sbcglobal.net,Zygmunt Oparowski,President
1,A-10119-96737,Certified-Expired,3/29/2010,10/18/2019,Y,9/15/2000,MARYLAND,N,FIL PARONG,13528 JAMIESON PL,NaN,GERMANTOWN,MARYLAND,UNITED STATES OF AMERICA,20874,301-515-8079,NaN,0.0,2009.0,531110,N,FIL PARONG,13528 JAMIESON PL,NaN,GERMANTOWN,MARYLAND,UNITED STATES OF AMERICA,20874,(301) 515-8079,NaN,WINSTON W TSAI,"WINSTON TSAI, ESQ.",(301) 320- 1888,NaN,6202 WINSTON DRIVE,NaN,BETHESDA,MARYLAND,UNITED STATES OF AMERICA,20817,WINSTONTSAI@AOL.COM,MD00020468,49-9042.00,"MAINTENANCE REPAIR WORKER, GENERAL",Level III,$19.36,Hour,OES,NaN,12/15/2009,12/14/2010,$19.36,NaN,Hour,4242 RED MAPLE COUNT,4242 RED MAPLE COUNT,BURTONSVILLE,MARYLAND,20866,MAINTENANCE REPAIRER,High School,NaN,NaN,N,NaN,NaN,N,24.0,N,NaN,N,NaN,NaN,NaN,Y,N,NaN,NaN,Y,N,MUST HAVE 24 MONTHS EXPERIENCE FOR MAINTENANCE...,N,Y,N,N,NaN,N,N,N,N,NaN,NaN,NaN,1/6/2010,2/7/2010,Y,WASHINGTON EXAMINER,2/7/2010,WASHINGTON EXAMINER,Newspaper,2/14/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,Y,N,NaN,PHILIPPINES,PHILIPPINES,B-2,High School,NaN,HIGH SCHOOL,1991.0,SAN JACINTO NATIONAL HIGH SCHOOL,10 BARANGAY GUIBEL ST,NaN,SAN JACINTO,BARANGAY,PHILIPPINES,NaN,NaN,Y,NaN,NaN,N,N,N,N,WINSTON W TSAI,ATTORNEY AT LAW,WINSTONTSAI@AOL.COM,FIL PARONG,HEAD OF HOUSEHOLD
2,A-10225-13679,Denied,8/10/2010,4/30/2020,N,NaN,NaN,N,GLENNS PLUMBING SERVICES,854 CUSTER STREET,NaN,N. VALLEY STREAM,NEW YORK,UNITED STATES OF AMERICA,11580,516-561-3692,NaN,3.0,2002.0,NaN,N,DAVID GLENN,854 CUSTER STREET,NaN,N. VALLEY STREAM,NEW YORK,UNITED STATES OF AMERICA,11580,516-561-3692,NaN,DANIEL J SULLIVAN,"DANIEL J. SULLIVAN, ESQ.",631-732-3516,NaN,815 HORSEBLOCK ROAD,NaN,FARMINGVILLE,NEW YORK,UNITED STATES OF AMERICA,11738,GWG8@AOL.COM,P10010067706999,47-2152.02,PLUMBER,Level IV,"$78,645.00",Year,OES,NaN,5/5/2010,8/3/2010,$38.00,$40.00,Hour,854 Custer Street,NaN,North Valley Stream,NEW YORK,11580,PLUMBER,None,NaN,NaN,N,NaN,NaN,Y,24.0,N,NaN,N,NaN,NaN,NaN,N,N,NaN,NaN,Y,N,ABILITY TO COMMUNICATE FLUENTLY IN SPANISH.,N,Y,N,N,N,N,N,N,N,NaN,NaN,NaN,5/3/2010,8/13/2010,Y,NY Post,6/6/2010,NY Post,Newspaper,6/13/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,Y,N,N,EL SALVADOR,EL SALVADOR,EWI,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,Y,N,N,N,N,N,N,DANIEL J SULLIVAN,ATTORNEY,GWG8@AOL.COM,DAVID GLENN,OWNER
3,A-11033-51540,Certified,2/3/2011,5/28/2020,N,NaN,NaN,N,SKILLNET SOLUTIONS INC.,1901 SOUTH BASCOM AVENUE,SUITE 600,CAMPBELL,CALIFORNIA,UNITED STATES OF AMERICA,95008,408-523-6225,NaN,29.0,1996.0,519190,N,Jack Grover,1151 Sonora Court,Suite 2,Sunnyvale,CALIFORNIA,UNITED STATES OF AMERICA,94086,408-523-6225,jack@skillnetinc.com,Sonal Kinger,Baker Law Corporation,(408) 971-0282,NaN,"111 North Market Street,",Suite 300,San Jose,CALIFORNIA,UNITED STATES OF AMERICA,95113,sonal.kinger@bakerlawcorp.com,P10010223453518,15-1031.00,"Comp. SWE, Applications",Level IV,"$131,518.00",Year,OES,NaN,8/27/2010,6/30/2011,"$131,518.00",NaN,Year,1151 Sonora Court,Suite 2,Sunnyvale,CALIFORNIA,94086,Programmer Analyst,Bachelor's,NaN,Computer Science,N,NaN,NaN,Y,60.0,Y,"SWE, Computer Applications or rltd",Y,Other,BS equivalency based on combination of diplomas,5.0,Y,Y,60.0,"Programmer Analyst, SWE, Junior Office, Lab As...",Y,N,Position requires Bachelors degree or foreign ...,N,Y,N,N,NaN,Y,N,NaN,NaN,NaN,NaN,NaN,9/9/2010,10/11/2010,Y,San Jose Mercury News,10/10/2010,San Jose Mercury News,Newspaper,10/17/2010,NaN,NaN,NaN,NaN,9/14/2010,9/28/2010,NaN,NaN,10/10/2010,10/15/2010,NaN,NaN,9/13/2010,9/27/2010,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,Y,N,NaN,INDIA,INDIA,H-1B,Other,EQUIV. OF BS BASED ON COMBO OF DIPLOMAS,ELECTRONICS ENGINEERING COMPUTER SCIENCE,1996.0,SHRI BAHAGUBHAI MAFATLAL POLYTECHNIC INSTITUTE,"IRLA LANE, VILE PARLE W",NaN,MUMBAI,MAHARASHTRA,INDIA,400056,NaN,Y,Y,Y,N,N,Y,N,Sonal Kinger,Attorney at Law,sonal.kinger@bakerlawcorp.com,Jack Grover,VP of Finance and Operations
4,A-11074-62984,Denied,3/10/2011,6/17/2020,N,NaN,NaN,N,"R L CONSTRUCTION, INC.",904 NEPPERHAN AVENUE,NaN,YONKERS,NEW YORK,UNITED STATES OF AMERICA,10703,(914) 423-2400,NaN,43.0,1987.0,236115,N,RITA O ' SULLIVAN,904 NEPPERHAN AVENUE,NaN,YONKERS,NEW YORK,UNITED STATES OF AMERICA,10703,(914) 423-2400,ROSULLIVAN@RLCON.COM,VERNON L DUTTON,NON ATTORNEY,(718) 356-0592,NaN,130 NANCY LANE,NaN,STATEN ISLAND,NEW YORK,UNITED STATES OF AMERICA,10307,MRDUTTON@VERIZON.NET,P10010244002722,47-1011.01,FIRST LINE SUPERVISORS CONSTRUCTION TRADES WO...,Level I,"$53,643.00",Year,OES,NaN,9/17/2010,7/1/2011,"$53,643.00",NaN,Year,904 NEPPERHAN AVENUE,NaN,YONKERS,NEW YORK,10703,PROJECT MANAGER,None,NaN,NaN,N,NaN,NaN,Y,24.0,N,NaN,N,NaN,NaN,NaN,N,N,NaN,NaN,Y,N,NaN,N,Y,N,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,11/3/2010,12/3/2010,Y,NEW YORK POST,10/17/2010,NEW YORK POST,Newspaper,10/24/2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,Y,N,NaN,IRELAND,IRELAND,NaN,High School,NaN,GENERAL,1995.0,FALCARRAGH HIGH SCHOOL,NaN,NaN,FALCARRAGH,NaN,IRELAND,NaN,NaN,Y,NaN,NaN,N,N,N,N,DENISE S DUTTON,NONATTORNEY,NaN,RITA O SULLIVAN,MANAGER

In [16]:
# Check rows
project.shape

(71942, 154)

In [17]:
# Select only meaninful columns
project = project[['CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE', 'EMPLOYER_CITY', 'EMPLOYER_STATE_PROVINCE',
                   'EMPLOYER_NUM_EMPLOYEES', 'EMP_CONTACT_CITY', 'EMP_CONTACT_STATE_PROVINCE', 'EMP_CONTACT_POSTAL_CODE',
                   'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_FIRM_NAME', 'PW_SKILL_LEVEL', 'PW_WAGE', 'PW_UNIT_OF_PAY',
                   'WORKSITE_CITY', 'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'REQUIRED_EXPERIENCE', 
                   'REQUIRED_EXPERIENCE_MONTHS', 'WAGE_OFFER_UNIT_OF_PAY', 'PW_SOC_CODE', 
                   'FOREIGN_LANGUAGE_REQUIRED', 'FIRST_NEWSPAPER_NAME', 'SECOND_NEWSPAPER_AD_NAME', 
                   'COUNTRY_OF_CITIZENSHIP', 'FOREIGN_WORKER_BIRTH_COUNTRY', 'CLASS_OF_ADMISSION', 
                   'FOREIGN_WORKER_EDUCATION', 'FOREIGN_WORKER_INFO_MAJOR', 'FOREIGN_WORKER_INST_OF_ED',
                  'EMPLOYER_YEAR_COMMENCED_BUSINESS', 'NAICS_CODE', 'MINIMUM_EDUCATION']]

In [18]:
# Print types
project.dtypes

CASE_STATUS                          object
RECEIVED_DATE                        object
DECISION_DATE                        object
EMPLOYER_CITY                        object
EMPLOYER_STATE_PROVINCE              object
EMPLOYER_NUM_EMPLOYEES              float64
EMP_CONTACT_CITY                     object
EMP_CONTACT_STATE_PROVINCE           object
EMP_CONTACT_POSTAL_CODE              object
AGENT_ATTORNEY_NAME                  object
AGENT_ATTORNEY_FIRM_NAME             object
PW_SKILL_LEVEL                       object
PW_WAGE                              object
PW_UNIT_OF_PAY                       object
WORKSITE_CITY                        object
WORKSITE_STATE                       object
WORKSITE_POSTAL_CODE                 object
REQUIRED_EXPERIENCE                  object
REQUIRED_EXPERIENCE_MONTHS          float64
WAGE_OFFER_UNIT_OF_PAY               object
PW_SOC_CODE                          object
FOREIGN_LANGUAGE_REQUIRED            object
FIRST_NEWSPAPER_NAME                 object
SECOND_NEWSPAPER_AD_NAME             object
COUNTRY_OF_CITIZENSHIP               object
FOREIGN_WORKER_BIRTH_COUNTRY         object
CLASS_OF_ADMISSION                   object
FOREIGN_WORKER_EDUCATION             object
FOREIGN_WORKER_INFO_MAJOR            object
FOREIGN_WORKER_INST_OF_ED            object
EMPLOYER_YEAR_COMMENCED_BUSINESS    float64
NAICS_CODE                           object
MINIMUM_EDUCATION                    object
dtype: object

In [19]:
# All column names to lower
project.columns = project.columns.str.lower()

In [20]:
# Print
project.head(5)

,case_status,received_date,decision_date,employer_city,employer_state_province,employer_num_employees,emp_contact_city,emp_contact_state_province,emp_contact_postal_code,agent_attorney_name,agent_attorney_firm_name,pw_skill_level,pw_wage,pw_unit_of_pay,worksite_city,worksite_state,worksite_postal_code,required_experience,required_experience_months,wage_offer_unit_of_pay,pw_soc_code,foreign_language_required,first_newspaper_name,second_newspaper_ad_name,country_of_citizenship,foreign_worker_birth_country,class_of_admission,foreign_worker_education,foreign_worker_info_major,foreign_worker_inst_of_ed,employer_year_commenced_business,naics_code,minimum_education
0,Denied,9/3/2009,4/30/2020,CHICAGO,ILLINOIS,2.0,chicago,ILLINOIS,60647,Christopher E Kurczaba,Kurczaba Law Offices,Level I,$14.49,Hour,Chicago,ILLINOIS,60647,Y,24.0,Hour,43-6011.00,Y,Chicago Tribune,Chicago Tribune,POLAND,POLAND,B-2,High School,GENERAL,LICEUM EKONOMICZNE,1998.0,23611,High School
1,Certified-Expired,3/29/2010,10/18/2019,GERMANTOWN,MARYLAND,0.0,GERMANTOWN,MARYLAND,20874,WINSTON W TSAI,"WINSTON TSAI, ESQ.",Level III,$19.36,Hour,BURTONSVILLE,MARYLAND,20866,N,24.0,Hour,49-9042.00,N,WASHINGTON EXAMINER,WASHINGTON EXAMINER,PHILIPPINES,PHILIPPINES,B-2,High School,HIGH SCHOOL,SAN JACINTO NATIONAL HIGH SCHOOL,2009.0,531110,High School
2,Denied,8/10/2010,4/30/2020,N. VALLEY STREAM,NEW YORK,3.0,N. VALLEY STREAM,NEW YORK,11580,DANIEL J SULLIVAN,"DANIEL J. SULLIVAN, ESQ.",Level IV,"$78,645.00",Year,North Valley Stream,NEW YORK,11580,Y,24.0,Hour,47-2152.02,N,NY Post,NY Post,EL SALVADOR,EL SALVADOR,EWI,None,NaN,NaN,2002.0,NaN,None
3,Certified,2/3/2011,5/28/2020,CAMPBELL,CALIFORNIA,29.0,Sunnyvale,CALIFORNIA,94086,Sonal Kinger,Baker Law Corporation,Level IV,"$131,518.00",Year,Sunnyvale,CALIFORNIA,94086,Y,60.0,Year,15-1031.00,N,San Jose Mercury News,San Jose Mercury News,INDIA,INDIA,H-1B,Other,ELECTRONICS ENGINEERING COMPUTER SCIENCE,SHRI BAHAGUBHAI MAFATLAL POLYTECHNIC INSTITUTE,1996.0,519190,Bachelor's
4,Denied,3/10/2011,6/17/2020,YONKERS,NEW YORK,43.0,YONKERS,NEW YORK,10703,VERNON L DUTTON,NON ATTORNEY,Level I,"$53,643.00",Year,YONKERS,NEW YORK,10703,Y,24.0,Year,47-1011.01,N,NEW YORK POST,NEW YORK POST,IRELAND,IRELAND,NaN,High School,GENERAL,FALCARRAGH HIGH SCHOOL,1987.0,236115,None

In [21]:
# Check NAs
project.isnull().sum(axis = 0)
# As we can see, there are some NAs

case_status                             0
received_date                           5
decision_date                           0
employer_city                           0
employer_state_province                 1
employer_num_employees                  9
emp_contact_city                        1
emp_contact_state_province              3
emp_contact_postal_code                 4
agent_attorney_name                     0
agent_attorney_firm_name             5956
pw_skill_level                       4303
pw_wage                                 8
pw_unit_of_pay                         10
worksite_city                           4
worksite_state                          4
worksite_postal_code                    5
required_experience                     2
required_experience_months          31220
wage_offer_unit_of_pay                  3
pw_soc_code                            46
foreign_language_required               0
first_newspaper_name                 1641
second_newspaper_ad_name             1652
country_of_citizenship                  6
foreign_worker_birth_country            5
class_of_admission                   5854
foreign_worker_education                5
foreign_worker_info_major            9160
foreign_worker_inst_of_ed            8669
employer_year_commenced_business       27
naics_code                             49
minimum_education                       6
dtype: int64

In [22]:
# Remove $ symbol
project = project.replace(r'[<$]', '', regex = True)

In [23]:
# Print
project.head(5)

,case_status,received_date,decision_date,employer_city,employer_state_province,employer_num_employees,emp_contact_city,emp_contact_state_province,emp_contact_postal_code,agent_attorney_name,agent_attorney_firm_name,pw_skill_level,pw_wage,pw_unit_of_pay,worksite_city,worksite_state,worksite_postal_code,required_experience,required_experience_months,wage_offer_unit_of_pay,pw_soc_code,foreign_language_required,first_newspaper_name,second_newspaper_ad_name,country_of_citizenship,foreign_worker_birth_country,class_of_admission,foreign_worker_education,foreign_worker_info_major,foreign_worker_inst_of_ed,employer_year_commenced_business,naics_code,minimum_education
0,Denied,9/3/2009,4/30/2020,CHICAGO,ILLINOIS,2.0,chicago,ILLINOIS,60647,Christopher E Kurczaba,Kurczaba Law Offices,Level I,14.49,Hour,Chicago,ILLINOIS,60647,Y,24.0,Hour,43-6011.00,Y,Chicago Tribune,Chicago Tribune,POLAND,POLAND,B-2,High School,GENERAL,LICEUM EKONOMICZNE,1998.0,23611,High School
1,Certified-Expired,3/29/2010,10/18/2019,GERMANTOWN,MARYLAND,0.0,GERMANTOWN,MARYLAND,20874,WINSTON W TSAI,"WINSTON TSAI, ESQ.",Level III,19.36,Hour,BURTONSVILLE,MARYLAND,20866,N,24.0,Hour,49-9042.00,N,WASHINGTON EXAMINER,WASHINGTON EXAMINER,PHILIPPINES,PHILIPPINES,B-2,High School,HIGH SCHOOL,SAN JACINTO NATIONAL HIGH SCHOOL,2009.0,531110,High School
2,Denied,8/10/2010,4/30/2020,N. VALLEY STREAM,NEW YORK,3.0,N. VALLEY STREAM,NEW YORK,11580,DANIEL J SULLIVAN,"DANIEL J. SULLIVAN, ESQ.",Level IV,"78,645.00",Year,North Valley Stream,NEW YORK,11580,Y,24.0,Hour,47-2152.02,N,NY Post,NY Post,EL SALVADOR,EL SALVADOR,EWI,None,NaN,NaN,2002.0,NaN,None
3,Certified,2/3/2011,5/28/2020,CAMPBELL,CALIFORNIA,29.0,Sunnyvale,CALIFORNIA,94086,Sonal Kinger,Baker Law Corporation,Level IV,"131,518.00",Year,Sunnyvale,CALIFORNIA,94086,Y,60.0,Year,15-1031.00,N,San Jose Mercury News,San Jose Mercury News,INDIA,INDIA,H-1B,Other,ELECTRONICS ENGINEERING COMPUTER SCIENCE,SHRI BAHAGUBHAI MAFATLAL POLYTECHNIC INSTITUTE,1996.0,519190,Bachelor's
4,Denied,3/10/2011,6/17/2020,YONKERS,NEW YORK,43.0,YONKERS,NEW YORK,10703,VERNON L DUTTON,NON ATTORNEY,Level I,"53,643.00",Year,YONKERS,NEW YORK,10703,Y,24.0,Year,47-1011.01,N,NEW YORK POST,NEW YORK POST,IRELAND,IRELAND,NaN,High School,GENERAL,FALCARRAGH HIGH SCHOOL,1987.0,236115,None

In [24]:
# Save as csv
project.to_csv('../Data/Clean/project_data_cleaned.csv')